//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SaleManagement.WebApp.CustomerService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IDNWebSerivesSoap", Namespace="http://idn.com.vn/BSGKG_WebSrv/")]
    public partial class IDNWebSerives : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IDN_EmpHistoryTrackingOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_EmpHistoryTracking_byEmpOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_DMS_CustVisited_Emp_ByEmpOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_DMS_EmpCurrLocationOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_DMS_EmpGroup_LoadOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_DMS_Province_LoadOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_DMS_Branch_LoadOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_DMS_Position_LoadOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_DMS_OCRD_SearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_ItemListSales_SearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_ROUTE_LoadOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_OSLP_LoadOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_CUST_GRP_LoadOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_CHANNEL_LoadOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_SmartPhone_LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_DMS_EmpCurrLocation_LoadOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_DMS_Employee_Monitor_LoadOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_DMS_CustVisited_Emp_LoadOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_WareHouseListOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_InOutReasonOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_ItemListOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_PDA_BIN_ByWhs_CheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_ItemInfo_ByBarCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_GetBinCodefromBarCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_InsertItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_DMS_OCRD_LoadOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDN_DMS_OCRD_LoadbyCardcodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IDNWebSerives() {
            this.Url = global::SaleManagement.WebApp.Properties.Settings.Default.SaleManagement_WebApp_CustomerService_IDNWebSerives;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IDN_EmpHistoryTrackingCompletedEventHandler IDN_EmpHistoryTrackingCompleted;
        
        /// <remarks/>
        public event IDN_EmpHistoryTracking_byEmpCompletedEventHandler IDN_EmpHistoryTracking_byEmpCompleted;
        
        /// <remarks/>
        public event IDN_DMS_CustVisited_Emp_ByEmpCompletedEventHandler IDN_DMS_CustVisited_Emp_ByEmpCompleted;
        
        /// <remarks/>
        public event IDN_DMS_EmpCurrLocationCompletedEventHandler IDN_DMS_EmpCurrLocationCompleted;
        
        /// <remarks/>
        public event IDN_DMS_EmpGroup_LoadCompletedEventHandler IDN_DMS_EmpGroup_LoadCompleted;
        
        /// <remarks/>
        public event IDN_DMS_Province_LoadCompletedEventHandler IDN_DMS_Province_LoadCompleted;
        
        /// <remarks/>
        public event IDN_DMS_Branch_LoadCompletedEventHandler IDN_DMS_Branch_LoadCompleted;
        
        /// <remarks/>
        public event IDN_DMS_Position_LoadCompletedEventHandler IDN_DMS_Position_LoadCompleted;
        
        /// <remarks/>
        public event IDN_DMS_OCRD_SearchCompletedEventHandler IDN_DMS_OCRD_SearchCompleted;
        
        /// <remarks/>
        public event IDN_ItemListSales_SearchCompletedEventHandler IDN_ItemListSales_SearchCompleted;
        
        /// <remarks/>
        public event IDN_ROUTE_LoadCompletedEventHandler IDN_ROUTE_LoadCompleted;
        
        /// <remarks/>
        public event IDN_OSLP_LoadCompletedEventHandler IDN_OSLP_LoadCompleted;
        
        /// <remarks/>
        public event IDN_CUST_GRP_LoadCompletedEventHandler IDN_CUST_GRP_LoadCompleted;
        
        /// <remarks/>
        public event IDN_CHANNEL_LoadCompletedEventHandler IDN_CHANNEL_LoadCompleted;
        
        /// <remarks/>
        public event IDN_SmartPhone_LoginCompletedEventHandler IDN_SmartPhone_LoginCompleted;
        
        /// <remarks/>
        public event IDN_DMS_EmpCurrLocation_LoadCompletedEventHandler IDN_DMS_EmpCurrLocation_LoadCompleted;
        
        /// <remarks/>
        public event IDN_DMS_Employee_Monitor_LoadCompletedEventHandler IDN_DMS_Employee_Monitor_LoadCompleted;
        
        /// <remarks/>
        public event IDN_DMS_CustVisited_Emp_LoadCompletedEventHandler IDN_DMS_CustVisited_Emp_LoadCompleted;
        
        /// <remarks/>
        public event IDN_WareHouseListCompletedEventHandler IDN_WareHouseListCompleted;
        
        /// <remarks/>
        public event IDN_InOutReasonCompletedEventHandler IDN_InOutReasonCompleted;
        
        /// <remarks/>
        public event IDN_ItemListCompletedEventHandler IDN_ItemListCompleted;
        
        /// <remarks/>
        public event IDN_PDA_BIN_ByWhs_CheckCompletedEventHandler IDN_PDA_BIN_ByWhs_CheckCompleted;
        
        /// <remarks/>
        public event IDN_ItemInfo_ByBarCodeCompletedEventHandler IDN_ItemInfo_ByBarCodeCompleted;
        
        /// <remarks/>
        public event IDN_GetBinCodefromBarCodeCompletedEventHandler IDN_GetBinCodefromBarCodeCompleted;
        
        /// <remarks/>
        public event IDN_InsertItemCompletedEventHandler IDN_InsertItemCompleted;
        
        /// <remarks/>
        public event IDN_DMS_OCRD_LoadCompletedEventHandler IDN_DMS_OCRD_LoadCompleted;
        
        /// <remarks/>
        public event IDN_DMS_OCRD_LoadbyCardcodeCompletedEventHandler IDN_DMS_OCRD_LoadbyCardcodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_EmpHistoryTracking", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_EmpHistoryTracking(string UserCode, string Branch, string Province, string Position, string EmpGrp, System.DateTime CurrDate, string FreeText) {
            object[] results = this.Invoke("IDN_EmpHistoryTracking", new object[] {
                        UserCode,
                        Branch,
                        Province,
                        Position,
                        EmpGrp,
                        CurrDate,
                        FreeText});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_EmpHistoryTrackingAsync(string UserCode, string Branch, string Province, string Position, string EmpGrp, System.DateTime CurrDate, string FreeText) {
            this.IDN_EmpHistoryTrackingAsync(UserCode, Branch, Province, Position, EmpGrp, CurrDate, FreeText, null);
        }
        
        /// <remarks/>
        public void IDN_EmpHistoryTrackingAsync(string UserCode, string Branch, string Province, string Position, string EmpGrp, System.DateTime CurrDate, string FreeText, object userState) {
            if ((this.IDN_EmpHistoryTrackingOperationCompleted == null)) {
                this.IDN_EmpHistoryTrackingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_EmpHistoryTrackingOperationCompleted);
            }
            this.InvokeAsync("IDN_EmpHistoryTracking", new object[] {
                        UserCode,
                        Branch,
                        Province,
                        Position,
                        EmpGrp,
                        CurrDate,
                        FreeText}, this.IDN_EmpHistoryTrackingOperationCompleted, userState);
        }
        
        private void OnIDN_EmpHistoryTrackingOperationCompleted(object arg) {
            if ((this.IDN_EmpHistoryTrackingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_EmpHistoryTrackingCompleted(this, new IDN_EmpHistoryTrackingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_EmpHistoryTracking_byEmp", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_EmpHistoryTracking_byEmp(string UserCode, System.DateTime CurrDate) {
            object[] results = this.Invoke("IDN_EmpHistoryTracking_byEmp", new object[] {
                        UserCode,
                        CurrDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_EmpHistoryTracking_byEmpAsync(string UserCode, System.DateTime CurrDate) {
            this.IDN_EmpHistoryTracking_byEmpAsync(UserCode, CurrDate, null);
        }
        
        /// <remarks/>
        public void IDN_EmpHistoryTracking_byEmpAsync(string UserCode, System.DateTime CurrDate, object userState) {
            if ((this.IDN_EmpHistoryTracking_byEmpOperationCompleted == null)) {
                this.IDN_EmpHistoryTracking_byEmpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_EmpHistoryTracking_byEmpOperationCompleted);
            }
            this.InvokeAsync("IDN_EmpHistoryTracking_byEmp", new object[] {
                        UserCode,
                        CurrDate}, this.IDN_EmpHistoryTracking_byEmpOperationCompleted, userState);
        }
        
        private void OnIDN_EmpHistoryTracking_byEmpOperationCompleted(object arg) {
            if ((this.IDN_EmpHistoryTracking_byEmpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_EmpHistoryTracking_byEmpCompleted(this, new IDN_EmpHistoryTracking_byEmpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_DMS_CustVisited_Emp_ByEmp", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_DMS_CustVisited_Emp_ByEmp(string UserCode, System.DateTime CurrDate) {
            object[] results = this.Invoke("IDN_DMS_CustVisited_Emp_ByEmp", new object[] {
                        UserCode,
                        CurrDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_DMS_CustVisited_Emp_ByEmpAsync(string UserCode, System.DateTime CurrDate) {
            this.IDN_DMS_CustVisited_Emp_ByEmpAsync(UserCode, CurrDate, null);
        }
        
        /// <remarks/>
        public void IDN_DMS_CustVisited_Emp_ByEmpAsync(string UserCode, System.DateTime CurrDate, object userState) {
            if ((this.IDN_DMS_CustVisited_Emp_ByEmpOperationCompleted == null)) {
                this.IDN_DMS_CustVisited_Emp_ByEmpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_DMS_CustVisited_Emp_ByEmpOperationCompleted);
            }
            this.InvokeAsync("IDN_DMS_CustVisited_Emp_ByEmp", new object[] {
                        UserCode,
                        CurrDate}, this.IDN_DMS_CustVisited_Emp_ByEmpOperationCompleted, userState);
        }
        
        private void OnIDN_DMS_CustVisited_Emp_ByEmpOperationCompleted(object arg) {
            if ((this.IDN_DMS_CustVisited_Emp_ByEmpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_DMS_CustVisited_Emp_ByEmpCompleted(this, new IDN_DMS_CustVisited_Emp_ByEmpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_DMS_EmpCurrLocation", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_DMS_EmpCurrLocation(string UserCode, string Branch, string Province, string Position, string EmpGrp, System.DateTime CurrDate, string FreeText) {
            object[] results = this.Invoke("IDN_DMS_EmpCurrLocation", new object[] {
                        UserCode,
                        Branch,
                        Province,
                        Position,
                        EmpGrp,
                        CurrDate,
                        FreeText});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_DMS_EmpCurrLocationAsync(string UserCode, string Branch, string Province, string Position, string EmpGrp, System.DateTime CurrDate, string FreeText) {
            this.IDN_DMS_EmpCurrLocationAsync(UserCode, Branch, Province, Position, EmpGrp, CurrDate, FreeText, null);
        }
        
        /// <remarks/>
        public void IDN_DMS_EmpCurrLocationAsync(string UserCode, string Branch, string Province, string Position, string EmpGrp, System.DateTime CurrDate, string FreeText, object userState) {
            if ((this.IDN_DMS_EmpCurrLocationOperationCompleted == null)) {
                this.IDN_DMS_EmpCurrLocationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_DMS_EmpCurrLocationOperationCompleted);
            }
            this.InvokeAsync("IDN_DMS_EmpCurrLocation", new object[] {
                        UserCode,
                        Branch,
                        Province,
                        Position,
                        EmpGrp,
                        CurrDate,
                        FreeText}, this.IDN_DMS_EmpCurrLocationOperationCompleted, userState);
        }
        
        private void OnIDN_DMS_EmpCurrLocationOperationCompleted(object arg) {
            if ((this.IDN_DMS_EmpCurrLocationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_DMS_EmpCurrLocationCompleted(this, new IDN_DMS_EmpCurrLocationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_DMS_EmpGroup_Load", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_DMS_EmpGroup_Load(string UserCode) {
            object[] results = this.Invoke("IDN_DMS_EmpGroup_Load", new object[] {
                        UserCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_DMS_EmpGroup_LoadAsync(string UserCode) {
            this.IDN_DMS_EmpGroup_LoadAsync(UserCode, null);
        }
        
        /// <remarks/>
        public void IDN_DMS_EmpGroup_LoadAsync(string UserCode, object userState) {
            if ((this.IDN_DMS_EmpGroup_LoadOperationCompleted == null)) {
                this.IDN_DMS_EmpGroup_LoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_DMS_EmpGroup_LoadOperationCompleted);
            }
            this.InvokeAsync("IDN_DMS_EmpGroup_Load", new object[] {
                        UserCode}, this.IDN_DMS_EmpGroup_LoadOperationCompleted, userState);
        }
        
        private void OnIDN_DMS_EmpGroup_LoadOperationCompleted(object arg) {
            if ((this.IDN_DMS_EmpGroup_LoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_DMS_EmpGroup_LoadCompleted(this, new IDN_DMS_EmpGroup_LoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_DMS_Province_Load", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_DMS_Province_Load(string UserCode) {
            object[] results = this.Invoke("IDN_DMS_Province_Load", new object[] {
                        UserCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_DMS_Province_LoadAsync(string UserCode) {
            this.IDN_DMS_Province_LoadAsync(UserCode, null);
        }
        
        /// <remarks/>
        public void IDN_DMS_Province_LoadAsync(string UserCode, object userState) {
            if ((this.IDN_DMS_Province_LoadOperationCompleted == null)) {
                this.IDN_DMS_Province_LoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_DMS_Province_LoadOperationCompleted);
            }
            this.InvokeAsync("IDN_DMS_Province_Load", new object[] {
                        UserCode}, this.IDN_DMS_Province_LoadOperationCompleted, userState);
        }
        
        private void OnIDN_DMS_Province_LoadOperationCompleted(object arg) {
            if ((this.IDN_DMS_Province_LoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_DMS_Province_LoadCompleted(this, new IDN_DMS_Province_LoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_DMS_Branch_Load", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_DMS_Branch_Load(string UserCode) {
            object[] results = this.Invoke("IDN_DMS_Branch_Load", new object[] {
                        UserCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_DMS_Branch_LoadAsync(string UserCode) {
            this.IDN_DMS_Branch_LoadAsync(UserCode, null);
        }
        
        /// <remarks/>
        public void IDN_DMS_Branch_LoadAsync(string UserCode, object userState) {
            if ((this.IDN_DMS_Branch_LoadOperationCompleted == null)) {
                this.IDN_DMS_Branch_LoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_DMS_Branch_LoadOperationCompleted);
            }
            this.InvokeAsync("IDN_DMS_Branch_Load", new object[] {
                        UserCode}, this.IDN_DMS_Branch_LoadOperationCompleted, userState);
        }
        
        private void OnIDN_DMS_Branch_LoadOperationCompleted(object arg) {
            if ((this.IDN_DMS_Branch_LoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_DMS_Branch_LoadCompleted(this, new IDN_DMS_Branch_LoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_DMS_Position_Load", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_DMS_Position_Load(string UserCode) {
            object[] results = this.Invoke("IDN_DMS_Position_Load", new object[] {
                        UserCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_DMS_Position_LoadAsync(string UserCode) {
            this.IDN_DMS_Position_LoadAsync(UserCode, null);
        }
        
        /// <remarks/>
        public void IDN_DMS_Position_LoadAsync(string UserCode, object userState) {
            if ((this.IDN_DMS_Position_LoadOperationCompleted == null)) {
                this.IDN_DMS_Position_LoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_DMS_Position_LoadOperationCompleted);
            }
            this.InvokeAsync("IDN_DMS_Position_Load", new object[] {
                        UserCode}, this.IDN_DMS_Position_LoadOperationCompleted, userState);
        }
        
        private void OnIDN_DMS_Position_LoadOperationCompleted(object arg) {
            if ((this.IDN_DMS_Position_LoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_DMS_Position_LoadCompleted(this, new IDN_DMS_Position_LoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_DMS_OCRD_Search", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_DMS_OCRD_Search(string UserCode, string Route, string Channel, string Group, int SalesManId, string FreeText) {
            object[] results = this.Invoke("IDN_DMS_OCRD_Search", new object[] {
                        UserCode,
                        Route,
                        Channel,
                        Group,
                        SalesManId,
                        FreeText});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_DMS_OCRD_SearchAsync(string UserCode, string Route, string Channel, string Group, int SalesManId, string FreeText) {
            this.IDN_DMS_OCRD_SearchAsync(UserCode, Route, Channel, Group, SalesManId, FreeText, null);
        }
        
        /// <remarks/>
        public void IDN_DMS_OCRD_SearchAsync(string UserCode, string Route, string Channel, string Group, int SalesManId, string FreeText, object userState) {
            if ((this.IDN_DMS_OCRD_SearchOperationCompleted == null)) {
                this.IDN_DMS_OCRD_SearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_DMS_OCRD_SearchOperationCompleted);
            }
            this.InvokeAsync("IDN_DMS_OCRD_Search", new object[] {
                        UserCode,
                        Route,
                        Channel,
                        Group,
                        SalesManId,
                        FreeText}, this.IDN_DMS_OCRD_SearchOperationCompleted, userState);
        }
        
        private void OnIDN_DMS_OCRD_SearchOperationCompleted(object arg) {
            if ((this.IDN_DMS_OCRD_SearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_DMS_OCRD_SearchCompleted(this, new IDN_DMS_OCRD_SearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_ItemListSales_Search", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_ItemListSales_Search(string UserCode, string FreeText) {
            object[] results = this.Invoke("IDN_ItemListSales_Search", new object[] {
                        UserCode,
                        FreeText});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_ItemListSales_SearchAsync(string UserCode, string FreeText) {
            this.IDN_ItemListSales_SearchAsync(UserCode, FreeText, null);
        }
        
        /// <remarks/>
        public void IDN_ItemListSales_SearchAsync(string UserCode, string FreeText, object userState) {
            if ((this.IDN_ItemListSales_SearchOperationCompleted == null)) {
                this.IDN_ItemListSales_SearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_ItemListSales_SearchOperationCompleted);
            }
            this.InvokeAsync("IDN_ItemListSales_Search", new object[] {
                        UserCode,
                        FreeText}, this.IDN_ItemListSales_SearchOperationCompleted, userState);
        }
        
        private void OnIDN_ItemListSales_SearchOperationCompleted(object arg) {
            if ((this.IDN_ItemListSales_SearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_ItemListSales_SearchCompleted(this, new IDN_ItemListSales_SearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_ROUTE_Load", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_ROUTE_Load(string UserCode) {
            object[] results = this.Invoke("IDN_ROUTE_Load", new object[] {
                        UserCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_ROUTE_LoadAsync(string UserCode) {
            this.IDN_ROUTE_LoadAsync(UserCode, null);
        }
        
        /// <remarks/>
        public void IDN_ROUTE_LoadAsync(string UserCode, object userState) {
            if ((this.IDN_ROUTE_LoadOperationCompleted == null)) {
                this.IDN_ROUTE_LoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_ROUTE_LoadOperationCompleted);
            }
            this.InvokeAsync("IDN_ROUTE_Load", new object[] {
                        UserCode}, this.IDN_ROUTE_LoadOperationCompleted, userState);
        }
        
        private void OnIDN_ROUTE_LoadOperationCompleted(object arg) {
            if ((this.IDN_ROUTE_LoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_ROUTE_LoadCompleted(this, new IDN_ROUTE_LoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_OSLP_Load", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_OSLP_Load(string UserCode) {
            object[] results = this.Invoke("IDN_OSLP_Load", new object[] {
                        UserCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_OSLP_LoadAsync(string UserCode) {
            this.IDN_OSLP_LoadAsync(UserCode, null);
        }
        
        /// <remarks/>
        public void IDN_OSLP_LoadAsync(string UserCode, object userState) {
            if ((this.IDN_OSLP_LoadOperationCompleted == null)) {
                this.IDN_OSLP_LoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_OSLP_LoadOperationCompleted);
            }
            this.InvokeAsync("IDN_OSLP_Load", new object[] {
                        UserCode}, this.IDN_OSLP_LoadOperationCompleted, userState);
        }
        
        private void OnIDN_OSLP_LoadOperationCompleted(object arg) {
            if ((this.IDN_OSLP_LoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_OSLP_LoadCompleted(this, new IDN_OSLP_LoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_CUST_GRP_Load", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_CUST_GRP_Load(string UserCode) {
            object[] results = this.Invoke("IDN_CUST_GRP_Load", new object[] {
                        UserCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_CUST_GRP_LoadAsync(string UserCode) {
            this.IDN_CUST_GRP_LoadAsync(UserCode, null);
        }
        
        /// <remarks/>
        public void IDN_CUST_GRP_LoadAsync(string UserCode, object userState) {
            if ((this.IDN_CUST_GRP_LoadOperationCompleted == null)) {
                this.IDN_CUST_GRP_LoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_CUST_GRP_LoadOperationCompleted);
            }
            this.InvokeAsync("IDN_CUST_GRP_Load", new object[] {
                        UserCode}, this.IDN_CUST_GRP_LoadOperationCompleted, userState);
        }
        
        private void OnIDN_CUST_GRP_LoadOperationCompleted(object arg) {
            if ((this.IDN_CUST_GRP_LoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_CUST_GRP_LoadCompleted(this, new IDN_CUST_GRP_LoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_CHANNEL_Load", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_CHANNEL_Load(string UserCode) {
            object[] results = this.Invoke("IDN_CHANNEL_Load", new object[] {
                        UserCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_CHANNEL_LoadAsync(string UserCode) {
            this.IDN_CHANNEL_LoadAsync(UserCode, null);
        }
        
        /// <remarks/>
        public void IDN_CHANNEL_LoadAsync(string UserCode, object userState) {
            if ((this.IDN_CHANNEL_LoadOperationCompleted == null)) {
                this.IDN_CHANNEL_LoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_CHANNEL_LoadOperationCompleted);
            }
            this.InvokeAsync("IDN_CHANNEL_Load", new object[] {
                        UserCode}, this.IDN_CHANNEL_LoadOperationCompleted, userState);
        }
        
        private void OnIDN_CHANNEL_LoadOperationCompleted(object arg) {
            if ((this.IDN_CHANNEL_LoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_CHANNEL_LoadCompleted(this, new IDN_CHANNEL_LoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_SmartPhone_Login", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_SmartPhone_Login(string UserCode, string Password) {
            object[] results = this.Invoke("IDN_SmartPhone_Login", new object[] {
                        UserCode,
                        Password});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_SmartPhone_LoginAsync(string UserCode, string Password) {
            this.IDN_SmartPhone_LoginAsync(UserCode, Password, null);
        }
        
        /// <remarks/>
        public void IDN_SmartPhone_LoginAsync(string UserCode, string Password, object userState) {
            if ((this.IDN_SmartPhone_LoginOperationCompleted == null)) {
                this.IDN_SmartPhone_LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_SmartPhone_LoginOperationCompleted);
            }
            this.InvokeAsync("IDN_SmartPhone_Login", new object[] {
                        UserCode,
                        Password}, this.IDN_SmartPhone_LoginOperationCompleted, userState);
        }
        
        private void OnIDN_SmartPhone_LoginOperationCompleted(object arg) {
            if ((this.IDN_SmartPhone_LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_SmartPhone_LoginCompleted(this, new IDN_SmartPhone_LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_DMS_EmpCurrLocation_Load", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_DMS_EmpCurrLocation_Load(string UserCode) {
            object[] results = this.Invoke("IDN_DMS_EmpCurrLocation_Load", new object[] {
                        UserCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_DMS_EmpCurrLocation_LoadAsync(string UserCode) {
            this.IDN_DMS_EmpCurrLocation_LoadAsync(UserCode, null);
        }
        
        /// <remarks/>
        public void IDN_DMS_EmpCurrLocation_LoadAsync(string UserCode, object userState) {
            if ((this.IDN_DMS_EmpCurrLocation_LoadOperationCompleted == null)) {
                this.IDN_DMS_EmpCurrLocation_LoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_DMS_EmpCurrLocation_LoadOperationCompleted);
            }
            this.InvokeAsync("IDN_DMS_EmpCurrLocation_Load", new object[] {
                        UserCode}, this.IDN_DMS_EmpCurrLocation_LoadOperationCompleted, userState);
        }
        
        private void OnIDN_DMS_EmpCurrLocation_LoadOperationCompleted(object arg) {
            if ((this.IDN_DMS_EmpCurrLocation_LoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_DMS_EmpCurrLocation_LoadCompleted(this, new IDN_DMS_EmpCurrLocation_LoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_DMS_Employee_Monitor_Load", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_DMS_Employee_Monitor_Load(string UserCode, System.DateTime MonitorDate) {
            object[] results = this.Invoke("IDN_DMS_Employee_Monitor_Load", new object[] {
                        UserCode,
                        MonitorDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_DMS_Employee_Monitor_LoadAsync(string UserCode, System.DateTime MonitorDate) {
            this.IDN_DMS_Employee_Monitor_LoadAsync(UserCode, MonitorDate, null);
        }
        
        /// <remarks/>
        public void IDN_DMS_Employee_Monitor_LoadAsync(string UserCode, System.DateTime MonitorDate, object userState) {
            if ((this.IDN_DMS_Employee_Monitor_LoadOperationCompleted == null)) {
                this.IDN_DMS_Employee_Monitor_LoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_DMS_Employee_Monitor_LoadOperationCompleted);
            }
            this.InvokeAsync("IDN_DMS_Employee_Monitor_Load", new object[] {
                        UserCode,
                        MonitorDate}, this.IDN_DMS_Employee_Monitor_LoadOperationCompleted, userState);
        }
        
        private void OnIDN_DMS_Employee_Monitor_LoadOperationCompleted(object arg) {
            if ((this.IDN_DMS_Employee_Monitor_LoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_DMS_Employee_Monitor_LoadCompleted(this, new IDN_DMS_Employee_Monitor_LoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_DMS_CustVisited_Emp_Load", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_DMS_CustVisited_Emp_Load(int EmpId, System.DateTime MonitorDate) {
            object[] results = this.Invoke("IDN_DMS_CustVisited_Emp_Load", new object[] {
                        EmpId,
                        MonitorDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_DMS_CustVisited_Emp_LoadAsync(int EmpId, System.DateTime MonitorDate) {
            this.IDN_DMS_CustVisited_Emp_LoadAsync(EmpId, MonitorDate, null);
        }
        
        /// <remarks/>
        public void IDN_DMS_CustVisited_Emp_LoadAsync(int EmpId, System.DateTime MonitorDate, object userState) {
            if ((this.IDN_DMS_CustVisited_Emp_LoadOperationCompleted == null)) {
                this.IDN_DMS_CustVisited_Emp_LoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_DMS_CustVisited_Emp_LoadOperationCompleted);
            }
            this.InvokeAsync("IDN_DMS_CustVisited_Emp_Load", new object[] {
                        EmpId,
                        MonitorDate}, this.IDN_DMS_CustVisited_Emp_LoadOperationCompleted, userState);
        }
        
        private void OnIDN_DMS_CustVisited_Emp_LoadOperationCompleted(object arg) {
            if ((this.IDN_DMS_CustVisited_Emp_LoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_DMS_CustVisited_Emp_LoadCompleted(this, new IDN_DMS_CustVisited_Emp_LoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_WareHouseList", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_WareHouseList() {
            object[] results = this.Invoke("IDN_WareHouseList", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_WareHouseListAsync() {
            this.IDN_WareHouseListAsync(null);
        }
        
        /// <remarks/>
        public void IDN_WareHouseListAsync(object userState) {
            if ((this.IDN_WareHouseListOperationCompleted == null)) {
                this.IDN_WareHouseListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_WareHouseListOperationCompleted);
            }
            this.InvokeAsync("IDN_WareHouseList", new object[0], this.IDN_WareHouseListOperationCompleted, userState);
        }
        
        private void OnIDN_WareHouseListOperationCompleted(object arg) {
            if ((this.IDN_WareHouseListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_WareHouseListCompleted(this, new IDN_WareHouseListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_InOutReason", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_InOutReason() {
            object[] results = this.Invoke("IDN_InOutReason", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_InOutReasonAsync() {
            this.IDN_InOutReasonAsync(null);
        }
        
        /// <remarks/>
        public void IDN_InOutReasonAsync(object userState) {
            if ((this.IDN_InOutReasonOperationCompleted == null)) {
                this.IDN_InOutReasonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_InOutReasonOperationCompleted);
            }
            this.InvokeAsync("IDN_InOutReason", new object[0], this.IDN_InOutReasonOperationCompleted, userState);
        }
        
        private void OnIDN_InOutReasonOperationCompleted(object arg) {
            if ((this.IDN_InOutReasonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_InOutReasonCompleted(this, new IDN_InOutReasonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_ItemList", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_ItemList() {
            object[] results = this.Invoke("IDN_ItemList", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_ItemListAsync() {
            this.IDN_ItemListAsync(null);
        }
        
        /// <remarks/>
        public void IDN_ItemListAsync(object userState) {
            if ((this.IDN_ItemListOperationCompleted == null)) {
                this.IDN_ItemListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_ItemListOperationCompleted);
            }
            this.InvokeAsync("IDN_ItemList", new object[0], this.IDN_ItemListOperationCompleted, userState);
        }
        
        private void OnIDN_ItemListOperationCompleted(object arg) {
            if ((this.IDN_ItemListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_ItemListCompleted(this, new IDN_ItemListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_PDA_BIN_ByWhs_Check", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_PDA_BIN_ByWhs_Check(string WhsCode, string BinCode) {
            object[] results = this.Invoke("IDN_PDA_BIN_ByWhs_Check", new object[] {
                        WhsCode,
                        BinCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_PDA_BIN_ByWhs_CheckAsync(string WhsCode, string BinCode) {
            this.IDN_PDA_BIN_ByWhs_CheckAsync(WhsCode, BinCode, null);
        }
        
        /// <remarks/>
        public void IDN_PDA_BIN_ByWhs_CheckAsync(string WhsCode, string BinCode, object userState) {
            if ((this.IDN_PDA_BIN_ByWhs_CheckOperationCompleted == null)) {
                this.IDN_PDA_BIN_ByWhs_CheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_PDA_BIN_ByWhs_CheckOperationCompleted);
            }
            this.InvokeAsync("IDN_PDA_BIN_ByWhs_Check", new object[] {
                        WhsCode,
                        BinCode}, this.IDN_PDA_BIN_ByWhs_CheckOperationCompleted, userState);
        }
        
        private void OnIDN_PDA_BIN_ByWhs_CheckOperationCompleted(object arg) {
            if ((this.IDN_PDA_BIN_ByWhs_CheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_PDA_BIN_ByWhs_CheckCompleted(this, new IDN_PDA_BIN_ByWhs_CheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_ItemInfo_ByBarCode", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_ItemInfo_ByBarCode(string BarCode) {
            object[] results = this.Invoke("IDN_ItemInfo_ByBarCode", new object[] {
                        BarCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_ItemInfo_ByBarCodeAsync(string BarCode) {
            this.IDN_ItemInfo_ByBarCodeAsync(BarCode, null);
        }
        
        /// <remarks/>
        public void IDN_ItemInfo_ByBarCodeAsync(string BarCode, object userState) {
            if ((this.IDN_ItemInfo_ByBarCodeOperationCompleted == null)) {
                this.IDN_ItemInfo_ByBarCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_ItemInfo_ByBarCodeOperationCompleted);
            }
            this.InvokeAsync("IDN_ItemInfo_ByBarCode", new object[] {
                        BarCode}, this.IDN_ItemInfo_ByBarCodeOperationCompleted, userState);
        }
        
        private void OnIDN_ItemInfo_ByBarCodeOperationCompleted(object arg) {
            if ((this.IDN_ItemInfo_ByBarCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_ItemInfo_ByBarCodeCompleted(this, new IDN_ItemInfo_ByBarCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_GetBinCodefromBarCode", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_GetBinCodefromBarCode(string BarCode, string WhsCode) {
            object[] results = this.Invoke("IDN_GetBinCodefromBarCode", new object[] {
                        BarCode,
                        WhsCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_GetBinCodefromBarCodeAsync(string BarCode, string WhsCode) {
            this.IDN_GetBinCodefromBarCodeAsync(BarCode, WhsCode, null);
        }
        
        /// <remarks/>
        public void IDN_GetBinCodefromBarCodeAsync(string BarCode, string WhsCode, object userState) {
            if ((this.IDN_GetBinCodefromBarCodeOperationCompleted == null)) {
                this.IDN_GetBinCodefromBarCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_GetBinCodefromBarCodeOperationCompleted);
            }
            this.InvokeAsync("IDN_GetBinCodefromBarCode", new object[] {
                        BarCode,
                        WhsCode}, this.IDN_GetBinCodefromBarCodeOperationCompleted, userState);
        }
        
        private void OnIDN_GetBinCodefromBarCodeOperationCompleted(object arg) {
            if ((this.IDN_GetBinCodefromBarCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_GetBinCodefromBarCodeCompleted(this, new IDN_GetBinCodefromBarCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_InsertItem", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_InsertItem(System.DateTime DocDate, string BarCode, string ItemName, double Quantity, string UoM, string WhsCode, string BINCode, string ReasonCode, string ToWhsCode, string ToBINCode) {
            object[] results = this.Invoke("IDN_InsertItem", new object[] {
                        DocDate,
                        BarCode,
                        ItemName,
                        Quantity,
                        UoM,
                        WhsCode,
                        BINCode,
                        ReasonCode,
                        ToWhsCode,
                        ToBINCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_InsertItemAsync(System.DateTime DocDate, string BarCode, string ItemName, double Quantity, string UoM, string WhsCode, string BINCode, string ReasonCode, string ToWhsCode, string ToBINCode) {
            this.IDN_InsertItemAsync(DocDate, BarCode, ItemName, Quantity, UoM, WhsCode, BINCode, ReasonCode, ToWhsCode, ToBINCode, null);
        }
        
        /// <remarks/>
        public void IDN_InsertItemAsync(System.DateTime DocDate, string BarCode, string ItemName, double Quantity, string UoM, string WhsCode, string BINCode, string ReasonCode, string ToWhsCode, string ToBINCode, object userState) {
            if ((this.IDN_InsertItemOperationCompleted == null)) {
                this.IDN_InsertItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_InsertItemOperationCompleted);
            }
            this.InvokeAsync("IDN_InsertItem", new object[] {
                        DocDate,
                        BarCode,
                        ItemName,
                        Quantity,
                        UoM,
                        WhsCode,
                        BINCode,
                        ReasonCode,
                        ToWhsCode,
                        ToBINCode}, this.IDN_InsertItemOperationCompleted, userState);
        }
        
        private void OnIDN_InsertItemOperationCompleted(object arg) {
            if ((this.IDN_InsertItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_InsertItemCompleted(this, new IDN_InsertItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_DMS_OCRD_Load", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_DMS_OCRD_Load(string UserCode) {
            object[] results = this.Invoke("IDN_DMS_OCRD_Load", new object[] {
                        UserCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_DMS_OCRD_LoadAsync(string UserCode) {
            this.IDN_DMS_OCRD_LoadAsync(UserCode, null);
        }
        
        /// <remarks/>
        public void IDN_DMS_OCRD_LoadAsync(string UserCode, object userState) {
            if ((this.IDN_DMS_OCRD_LoadOperationCompleted == null)) {
                this.IDN_DMS_OCRD_LoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_DMS_OCRD_LoadOperationCompleted);
            }
            this.InvokeAsync("IDN_DMS_OCRD_Load", new object[] {
                        UserCode}, this.IDN_DMS_OCRD_LoadOperationCompleted, userState);
        }
        
        private void OnIDN_DMS_OCRD_LoadOperationCompleted(object arg) {
            if ((this.IDN_DMS_OCRD_LoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_DMS_OCRD_LoadCompleted(this, new IDN_DMS_OCRD_LoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idn.com.vn/BSGKG_WebSrv/IDN_DMS_OCRD_LoadbyCardcode", RequestNamespace="http://idn.com.vn/BSGKG_WebSrv/", ResponseNamespace="http://idn.com.vn/BSGKG_WebSrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IDN_DMS_OCRD_LoadbyCardcode(string CardCode) {
            object[] results = this.Invoke("IDN_DMS_OCRD_LoadbyCardcode", new object[] {
                        CardCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IDN_DMS_OCRD_LoadbyCardcodeAsync(string CardCode) {
            this.IDN_DMS_OCRD_LoadbyCardcodeAsync(CardCode, null);
        }
        
        /// <remarks/>
        public void IDN_DMS_OCRD_LoadbyCardcodeAsync(string CardCode, object userState) {
            if ((this.IDN_DMS_OCRD_LoadbyCardcodeOperationCompleted == null)) {
                this.IDN_DMS_OCRD_LoadbyCardcodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDN_DMS_OCRD_LoadbyCardcodeOperationCompleted);
            }
            this.InvokeAsync("IDN_DMS_OCRD_LoadbyCardcode", new object[] {
                        CardCode}, this.IDN_DMS_OCRD_LoadbyCardcodeOperationCompleted, userState);
        }
        
        private void OnIDN_DMS_OCRD_LoadbyCardcodeOperationCompleted(object arg) {
            if ((this.IDN_DMS_OCRD_LoadbyCardcodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDN_DMS_OCRD_LoadbyCardcodeCompleted(this, new IDN_DMS_OCRD_LoadbyCardcodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_EmpHistoryTrackingCompletedEventHandler(object sender, IDN_EmpHistoryTrackingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_EmpHistoryTrackingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_EmpHistoryTrackingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_EmpHistoryTracking_byEmpCompletedEventHandler(object sender, IDN_EmpHistoryTracking_byEmpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_EmpHistoryTracking_byEmpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_EmpHistoryTracking_byEmpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_DMS_CustVisited_Emp_ByEmpCompletedEventHandler(object sender, IDN_DMS_CustVisited_Emp_ByEmpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_DMS_CustVisited_Emp_ByEmpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_DMS_CustVisited_Emp_ByEmpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_DMS_EmpCurrLocationCompletedEventHandler(object sender, IDN_DMS_EmpCurrLocationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_DMS_EmpCurrLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_DMS_EmpCurrLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_DMS_EmpGroup_LoadCompletedEventHandler(object sender, IDN_DMS_EmpGroup_LoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_DMS_EmpGroup_LoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_DMS_EmpGroup_LoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_DMS_Province_LoadCompletedEventHandler(object sender, IDN_DMS_Province_LoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_DMS_Province_LoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_DMS_Province_LoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_DMS_Branch_LoadCompletedEventHandler(object sender, IDN_DMS_Branch_LoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_DMS_Branch_LoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_DMS_Branch_LoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_DMS_Position_LoadCompletedEventHandler(object sender, IDN_DMS_Position_LoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_DMS_Position_LoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_DMS_Position_LoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_DMS_OCRD_SearchCompletedEventHandler(object sender, IDN_DMS_OCRD_SearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_DMS_OCRD_SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_DMS_OCRD_SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_ItemListSales_SearchCompletedEventHandler(object sender, IDN_ItemListSales_SearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_ItemListSales_SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_ItemListSales_SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_ROUTE_LoadCompletedEventHandler(object sender, IDN_ROUTE_LoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_ROUTE_LoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_ROUTE_LoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_OSLP_LoadCompletedEventHandler(object sender, IDN_OSLP_LoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_OSLP_LoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_OSLP_LoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_CUST_GRP_LoadCompletedEventHandler(object sender, IDN_CUST_GRP_LoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_CUST_GRP_LoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_CUST_GRP_LoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_CHANNEL_LoadCompletedEventHandler(object sender, IDN_CHANNEL_LoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_CHANNEL_LoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_CHANNEL_LoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_SmartPhone_LoginCompletedEventHandler(object sender, IDN_SmartPhone_LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_SmartPhone_LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_SmartPhone_LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_DMS_EmpCurrLocation_LoadCompletedEventHandler(object sender, IDN_DMS_EmpCurrLocation_LoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_DMS_EmpCurrLocation_LoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_DMS_EmpCurrLocation_LoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_DMS_Employee_Monitor_LoadCompletedEventHandler(object sender, IDN_DMS_Employee_Monitor_LoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_DMS_Employee_Monitor_LoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_DMS_Employee_Monitor_LoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_DMS_CustVisited_Emp_LoadCompletedEventHandler(object sender, IDN_DMS_CustVisited_Emp_LoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_DMS_CustVisited_Emp_LoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_DMS_CustVisited_Emp_LoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_WareHouseListCompletedEventHandler(object sender, IDN_WareHouseListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_WareHouseListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_WareHouseListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_InOutReasonCompletedEventHandler(object sender, IDN_InOutReasonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_InOutReasonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_InOutReasonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_ItemListCompletedEventHandler(object sender, IDN_ItemListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_ItemListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_ItemListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_PDA_BIN_ByWhs_CheckCompletedEventHandler(object sender, IDN_PDA_BIN_ByWhs_CheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_PDA_BIN_ByWhs_CheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_PDA_BIN_ByWhs_CheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_ItemInfo_ByBarCodeCompletedEventHandler(object sender, IDN_ItemInfo_ByBarCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_ItemInfo_ByBarCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_ItemInfo_ByBarCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_GetBinCodefromBarCodeCompletedEventHandler(object sender, IDN_GetBinCodefromBarCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_GetBinCodefromBarCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_GetBinCodefromBarCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_InsertItemCompletedEventHandler(object sender, IDN_InsertItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_InsertItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_InsertItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_DMS_OCRD_LoadCompletedEventHandler(object sender, IDN_DMS_OCRD_LoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_DMS_OCRD_LoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_DMS_OCRD_LoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IDN_DMS_OCRD_LoadbyCardcodeCompletedEventHandler(object sender, IDN_DMS_OCRD_LoadbyCardcodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDN_DMS_OCRD_LoadbyCardcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDN_DMS_OCRD_LoadbyCardcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591